### ISSUE TITLE
Error when applying GPX.

### ISSUE THREAD

**Issue by sun-jiao** [picode7/inaturalist-plugin#6]
TypeError: elTrackPoint.getElementsByTagName(...)[0] is undefined gpx.ts:23:41
    readGPX gpx.ts:23
    onclick main.ts:18
    openTextFile files.ts:19
    (async：EventListener.handleEvent)
    openTextFile files.ts:17
    (async：EventListener.handleEvent)
    openTextFile files.ts:10
    onclick main.ts:17

[S104070045.gpx](https://github.com/user-attachments/files/16838751/S104070045.txt)

**Comment by picode7** [comment]
Hi @sun-jiao, 
Thanks a lot for the report! 

Looks like your GPX-File is missing timestamps on the GPS-Points. Without these it won't be possible to match the time of the photographs taken with a GPS-Point (or in-between two points).

It would need a timestamp like this for each track point:
```xml
<trkpt lon="114.41333583" lat="30.54507502" time="2024-09-02T14:22:00Z"></trkpt>
```

See also https://en.wikipedia.org/wiki/GPS_Exchange_Format

---

However, I will look into giving the user a helpful error, instead of failing silently!

**Comment by picode7** [comment]
It will show like this:
![image](https://github.com/user-attachments/assets/2803b40e-80fe-404c-95da-eb6623052078)

**Comment by sun-jiao** [comment]
OK. Thanks.
